### ISSUE TITLE
T&F: bibstem discrepancies

### ISSUE THREAD

**Issue by csgrant00** [adsabs/ADSManualParser#27] opened 2023-08-08 16:42 UTC
MatST vs. MSTec
python run.py -p "/proj/ads/abstracts/data/T+F/TF.080823/ymst20.v039.i14/02670836.2023.2184577.xml" -t jats -f tf.test

IJSS vs. IJSSc
python run.py -p "/proj/ads/abstracts/data/T+F/TF.080823/tsys20.v054.i11/00207721.2023.2230963.xml" -t jats -f tf.test

PhaTr vs. PTMJ
python run.py -p "/proj/ads/abstracts/data/T+F/TF.080823/gpht20.v096.i08/01411594.2023.2223335.xml"  -t jats -f tf.test

**Comment by seasidesparrow** [comment] 2024-02-23 20:15
Closing -- the issue is with data in journals_database rather than ManualParser.  I'll adjust journalsdb as needed.

**Closed by seasidesparrow** 2024-02-23 20:15 UTC
